### ISSUE TITLE
Exo 2

### ISSUE THREAD

**Issue by gaspaonrocks** [Jonathancollinet/suite02#1]
Should I write it in English ?

Bon c'est pour pinailler un peu, mais dans l'exo 2, l'intitulé peut être interprété comme étant : 
   - générer un nb random,
   - lui coller un °F ou un °C derrière,
   - le retourner.

Il faudrait peut-être ajouter une notion de conversion dans l'énoncé...

Encore une fois c'est pour pinailler...

**Comment by Jonathancollinet** [comment]
Effectivement, cela nécessite plus d'informations, je corrige ça.

Merci
